export const SELECT_IMAGE = 'SELECT_IMAGE'
export const DESELECT_IMAGE = 'DESELECT_IMAGE'
export const DELETE_SELECTED_IMAGES = 'DELETE_SELECTED_IMAGES'
export const SET_SELECTED_IMAGES = 'SET_SELECTED_IMAGES';
export const IMAGE_GALLERY = 'IMAGE_GALLERY';
